apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-kubernetes-lab-deployment
  labels:
    app: express-kubernetes-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-kubernetes-lab
  template:
    metadata:
      labels:
        app: express-kubernetes-lab
    spec:
      containers:
      - name: express-kubernetes-lab
        image: express-kubernetes-lab:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000