apiVersion: v1
kind: Service
metadata:
  name: express-kubernetes-lab-service
  labels:
    app: express-kubernetes-lab
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: express-kubernetes-lab
  type: LoadBalancer